services:
  duckdb-llm:
    build: .
    volumes:
      - ./:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    stdin_open: true  # Keep stdin open
    tty: true         # Allocate a pseudo-TTY
